name: Deploy to private server

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'yarn'
        
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Unit Tests
        run: yarn test

  deploy:
    name: Deploy to Private Server
    runs-on: ubuntu-latest
    needs: test
    
    steps:      
      - name: Set up SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TARGET_SERVER_IP }}
          username: ${{ secrets.TARGET_SERVER_USER }}
          key: ${{ secrets.TARGET_SERVER_SSH_KEY }}

          proxy_host: ${{ secrets.PROXY_SERVER_IP }}
          proxy_username: ${{ secrets.PROXY_SERVER_USER }}
          proxy_key: ${{ secrets.PROXY_SERVER_SSH_KEY }}
          proxy_port: ${{ secrets.PROXY_SERVER_PORT }}

          script: |
            echo "Deploying application..."

            # ১. কোনো কমান্ড ফেল করলে স্ক্রিপ্ট যেন থামে
            set -e

            # ২. Node, Yarn এবং PM2-এর Environment variables লোড করা
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export PATH=$PATH:$HOME/.nvm/versions/node/$(ls $HOME/.nvm/versions/node 2>/dev/null | tail -n 1)/bin:$HOME/.yarn/bin

            
            echo "🚀 Navigating to project..."
            cd ~/AWS-Practice-Blog-Repo

            echo "📥 Fetching latest code..."
            git pull origin main

            echo "📦 Installing dependencies..."
            yarn install --frozen-lockfile

            echo "🏗️ Building Next.js application..."
            yarn build

            echo "🔄 Restarting PM2 process..."
            pm2 restart blog-demo:3000

            echo "✅ Deployment completed successfully!"